# Generated by Django 5.1.1 on 2024-10-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secao1_imagemFundo', models.ImageField(upload_to='')),
                ('secao1_imagemAutor', models.ImageField(upload_to='')),
                ('secao1_titulo1', models.CharField(max_length=150)),
                ('secao1_titulo2', models.CharField(max_length=150)),
                ('secao1_descricao', models.TextField()),
                ('secao2_imagemFundo', models.ImageField(upload_to='')),
                ('secao2_titulo', models.CharField(max_length=150)),
                ('secao2_texto', models.TextField()),
                ('secao3_titulo', models.CharField(max_length=150)),
                ('leitor1_imagem', models.ImageField(upload_to='')),
                ('leitor1_texto', models.TextField()),
                ('leitor1_nome', models.CharField(max_length=150)),
                ('leitor2_imagem', models.ImageField(upload_to='')),
                ('leitor2_texto', models.TextField()),
                ('leitor2_nome', models.CharField(max_length=150)),
                ('leitor3_imagem', models.ImageField(upload_to='')),
                ('leitor3_texto', models.TextField()),
                ('leitor3_nome', models.CharField(max_length=150)),
                ('leitor4_imagem', models.ImageField(upload_to='')),
                ('leitor4_texto', models.TextField()),
                ('leitor4_nome', models.CharField(max_length=150)),
                ('leitor5_imagem', models.ImageField(upload_to='')),
                ('leitor5_texto', models.TextField()),
                ('leitor5_nome', models.CharField(max_length=150)),
                ('secao4_titulo', models.CharField(max_length=150)),
                ('secao4_texto', models.TextField()),
                ('secao4_imagem1', models.ImageField(upload_to='')),
                ('secao4_imagem2', models.ImageField(upload_to='')),
                ('secao5_texto', models.TextField()),
                ('secao5_botao', models.CharField(max_length=150)),
                ('secao5_imagemFundo', models.ImageField(upload_to='')),
            ],
        ),
    ]
