# Generated by Django 5.1.1 on 2024-10-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartaeleanor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='leitor1_imagem',
            field=models.ImageField(blank=True, upload_to='cartaeleanor'),
        ),
        migrations.AlterField(
            model_name='index',
            name='leitor2_imagem',
            field=models.ImageField(blank=True, upload_to='cartaeleanor'),
        ),
        migrations.AlterField(
            model_name='index',
            name='leitor3_imagem',
            field=models.ImageField(blank=True, upload_to='cartaeleanor'),
        ),
        migrations.AlterField(
            model_name='index',
            name='leitor4_imagem',
            field=models.ImageField(blank=True, upload_to='cartaeleanor'),
        ),
        migrations.AlterField(
            model_name='index',
            name='leitor5_imagem',
            field=models.ImageField(blank=True, upload_to='cartaeleanor'),
        ),
        migrations.AlterField(
            model_name='index',
            name='secao1_imagemAutor',
            field=models.ImageField(blank=True, upload_to='cartaeleanor'),
        ),
        migrations.AlterField(
            model_name='index',
            name='secao1_imagemFundo',
            field=models.ImageField(blank=True, upload_to='cartaeleanor'),
        ),
        migrations.AlterField(
            model_name='index',
            name='secao2_imagemFundo',
            field=models.ImageField(blank=True, upload_to='cartaeleanor'),
        ),
        migrations.AlterField(
            model_name='index',
            name='secao4_imagem1',
            field=models.ImageField(blank=True, upload_to='cartaeleanor'),
        ),
        migrations.AlterField(
            model_name='index',
            name='secao4_imagem2',
            field=models.ImageField(blank=True, upload_to='cartaeleanor'),
        ),
        migrations.AlterField(
            model_name='index',
            name='secao5_imagemFundo',
            field=models.ImageField(blank=True, upload_to='cartaeleanor'),
        ),
    ]
