# Generated by Django 5.1.1 on 2024-10-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartaeleanor', '0002_alter_index_leitor1_imagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField()),
                ('text2', models.TextField()),
                ('text3', models.TextField()),
                ('text4', models.TextField()),
                ('text5', models.TextField()),
                ('text6', models.TextField()),
                ('text7', models.TextField()),
                ('text8', models.TextField()),
                ('text9', models.TextField()),
                ('text10', models.TextField()),
                ('text11', models.TextField()),
                ('text12', models.TextField()),
                ('text13', models.TextField()),
                ('text14', models.TextField()),
                ('text15', models.TextField()),
                ('text16', models.TextField()),
                ('text17', models.TextField()),
                ('text18', models.TextField()),
                ('text19', models.TextField()),
                ('text20', models.TextField()),
            ],
        ),
    ]
