# Generated by Django 5.1.1 on 2024-10-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartaeleanor', '0003_indextext'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, upload_to='cartaeleanor')),
                ('image2', models.ImageField(blank=True, upload_to='cartaeleanor')),
                ('image3', models.ImageField(blank=True, upload_to='cartaeleanor')),
                ('image4', models.ImageField(blank=True, upload_to='cartaeleanor')),
                ('image5', models.ImageField(blank=True, upload_to='cartaeleanor')),
                ('image6', models.ImageField(blank=True, upload_to='cartaeleanor')),
                ('image7', models.ImageField(blank=True, upload_to='cartaeleanor')),
                ('image8', models.ImageField(blank=True, upload_to='cartaeleanor')),
            ],
        ),
    ]
