# Generated by Django 5.1.1 on 2024-10-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartaeleanor', '0004_indeximage'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg1', models.ImageField(blank=True, upload_to='cartaeleanor')),
                ('bg2', models.ImageField(blank=True, upload_to='cartaeleanor')),
            ],
        ),
        migrations.CreateModel(
            name='IndexPseudoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudoimage1', models.ImageField(blank=True, upload_to='cartaeleanor')),
            ],
        ),
    ]
